### ISSUE TITLE
[Bug] Story instance is left in an invalid state when it fails to retrieve page.

### ISSUE THREAD

**Issue by StuxSoftware** [tusing/reddit-ffn-bot#19]
Possible fix:
- Remove the try-except in `Story.__init__`

**Comment by tusing** [comment]
So I'm referencing #22 here because I had to close it (as defined). 

So I'm not sure what a clean way to work around these issues would be - at the moment I'm using ASCII encode/decode to replace bad characters with a '?' and passing stories that cause errors on creations, but are there better alternatives?

**Comment by StuxSoftware** [comment]
For links: Urlencode and Urldecode (see urllib)
For the rest: Decode xml entities (if not done automatically) and let the reddit library do the encoding work for you.

**Comment by StuxSoftware** [comment]
I have no idea if the problem is fixed now, but since I didn't get any error, I will close this issue now.
