### ISSUE TITLE
[Feature Request] Include Fandoms in fic-data.

### ISSUE THREAD

**Issue by StuxSoftware** [tusing/reddit-ffn-bot#23]
So you know if this is a Dagan Ropa fic or a HP fic. Or a crossover.

**Comment by tusing** [comment]
I'll see how to do this. At a cursory inspection, the XPaths are different (`//*[@id="pre_story_links"]/span/a`for some and `//*[@id="pre_story_links"]/span/a[2`] for others).

On top of that, I'm not even really sure what that entire library is - the code I've used so far was pretty much just guesswork and looking through a few guides quickly online. I'm sure there's probably a better way to handle this than manually finding the XPaths for each element - so if you have any ideas, I would be grateful.

Because if finding the XPaths are the fastest way, it's going to be some tedious work to add other fanfiction sites.

**Comment by StuxSoftware** [comment]
Get the last a-element
`//*[@id="pre_story_links"]/span/a[last()]`

**Comment by StuxSoftware** [comment]
XPath is one of the best solutions I know for scaping sites...
For the layer of indirection: See #25

**Comment by tusing** [comment]
Figured it out,: //text() instead of /test() gets e everything

On Sat, Jun 13, 2015, 12:06 PM StuxSoftware <notifications@github.com>
wrote:

> XPath is one of the best solutions I know for scaping sites...
> For the layer of indirection: See #25
> <https://github.com/tusing/reddit-ffn-bot/pull/25>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tusing/reddit-ffn-bot/issues/23#issuecomment-111724453>
> .
>
-- 

-- 

*Tushar Singal*

University of California, Berkeley | Class of 2018

Electrical Engineering and Computer Science | College of Engineering

(954) 699-9333| tusharsingal@berkeley.edu | tusharsingal@gmail.com

**Comment by tusing** [comment]
At a glance, this is just adding another XPath, so it shouldn't be difficult at all. I'll work on it when I get the chance.
