### ISSUE TITLE
[Enhancement] Update the docs?

### ISSUE THREAD

**Issue by StuxSoftware** [tusing/reddit-ffn-bot#32]

**Comment by tusing** [comment]
Will do. At the moment I won't be able to contribute much for about a day or two-ish, due to RL, but I'll surely update the docs eventually.

There are some formatting kinks we might want to work out before updating the docs. [This](http://www.reddit.com/r/tusingtestfield/comments/39qvo8/ao3_testing/cs5lsxu) happened when I tried to link AO3.

I also plan on getting around to writing docs for every function.

**Comment by StuxSoftware** [comment]
Well, it should work now.

**Comment by tusing** [comment]
Issue fixed, closing. No need to add more to the docs I think, just stating that the linkffn/linkao3/linkfp are interchangeable should be enough, rather than adding new examples
