### ISSUE TITLE
Sanity and Edit Checks

### ISSUE THREAD

**Issue by tusing** [tusing/reddit-ffn-bot#88]
I think we should add two things:

* **Sanity Checks** will make sure that the bot has replied to every FanfictionBot call. This will require changing from using ```checked_comments.txt``` to checking the *replies* to comments calling the bot. **If replies to a comment contain FanfictionBot as an author**, the bot will not respond. Otherwise, the bot will create a reply.

* **Edit Checks** will update FanfictionBot replies if the parent comment has updated their submission.

A fundamental change in this is that _we won't be using ```checked_comments.txt```_ to make sure we've replied to a comment - instead, we'll check the replies to every comment that calls the bot, instead.

**Comment by StuxSoftware** [comment]
It would be an idea.
But doesn't it generate a lot of traffic?

**Comment by tusing** [comment]
It does, and minimizing that would be something to consider. However, it has the potential to make the bot better - bot calls won't fail anymore and people won't have to call for parent if they edit their comment.  Any ideas?

**Comment by StuxSoftware** [comment]
Well, I still think that the bot should be manually asked to evaluate parent posts. Other than that, well I think we should not use edit checks. Doing so might break someones workflow, especially of those who do nut know much about formatting in reddit and don't want to have tags and calls appear in their post.

I think the ffnbot!parent keeps this somewhat friendly for non technically inclined users.
But otherwise, I would totally go for this change as it drops the checked comments.txt

**Comment by tusing** [comment]
Was looking into this a bit more. There are far too many edge cases to make the bot self-correcting. I do not have the time to isolate and solve for every edge case that might happen, so I don't see this happening any time soon.
