### ISSUE TITLE
[Feature Request]: Asking the bot to summarise and recommend *threads*.

### ISSUE THREAD

**Issue by DoorIntoSummer** [tusing/reddit-ffn-bot#91]
Many story requests repeat themselves once in a while, usually because OPs don’t search through the subreddit first or because a vague title/description combo made these threads harder to find.

I suggest adding an additional option for the bot to link and summarize subreddit threads as well.

---

I also had two other long-term feature reqs,^1 but I don’t know whether I should write about them here or open a new thread for each one.

^1: 
b) asking the bot via PMs to reply to not litter the thread comments with twice as much comments, 
c) archiving each story that gets downloaded (p0ody-files just converts them for downloading and discards them, AFAIK).

**Comment by stuxcrystal** [comment]
b) tusing is already working on it.

c) p0ody-files caches the stories.

 

Your main request:

What do you mean by that exactly?

 

Von: DoorIntoSummer [mailto:notifications@github.com] 
Gesendet: Samstag, 23. Januar 2016 21:14
An: tusing/reddit-ffn-bot <reddit-ffn-bot@noreply.github.com>
Betreff: [reddit-ffn-bot] [Feature Request]: Asking the bot to summarise and recommend /threads/. (#91)

 

Many story requests repeat themselves once in a while, usually because OPs don’t search through the subreddit first or because a vague title/description combo make these threads harder to find

I suggest adding an additional option for the bot to link and summarize subreddit threads as well

  _____  

I also had two other long-term features reqs,^1 but I don’t know whether I should write about them here or open a new thread for each one

^1: 
b) asking the bot via PMs to reply to not litter the thread comments with twice as much comments, 
c) archiving each story that gets downloaded (p0ody-files just converts them for downloading and discards them, AFAIK)

**Comment by tusing** [comment]
a) Would require a good analytics framework. The current in-development version of the bot on the master branch has some basic logging features, but we haven't implemented analytics yet. I've been considering ways to do that, but it's a bit difficult given the nature of fanfiction and the vague requests we get. The bot has to be both confident enough to correctly identify the subject of the thread, and have enough information to confidently construct a reply with recs or a similar thread. It's not your average "word cloud" problem, but it's something I'd be willing to look into during the summer, when I'll have more experience with AI/machine learning.

b) Implemented!

c) P0ody-files actually archives the stories. Having the bot archive every story would quickly eat up space. One of my long-term goals is actually having our own open-source fic downloader, so we are not dependent on any other website for our downloads.

**Comment by DoorIntoSummer** [comment]
> What do you mean by that exactly?
> Would require a good analytics framework.

To remove possible misunderstanding: I meant an ability for the bot to accept a link to a subreddit thread (e.g. `linksub(https://www.reddit.com/r/HPfanfiction/comments/3hsfw0/)` or maybe `linksub(3hsfw0)`, if that would be a unique enough ID to work), and return things like its creation date, title, opener’s nick, rating score, and number of detected fanfics listed there (not even parsing each of those links — just telling that “so many stories have been linked in that thread”).

My perspective on the usefulness of such a feature may be skewed, so this too of course is only a request for consideration.

> b) Implemented!

Do you mean the latest update? I thought it only answered to the requester via PM giving them an already parsed\formatted info for the story they requested (in contrast to the bot receiving a PM with story ID1 and thread ID2 and replying with the ID1!story’s parsed info to the ID2!thread). 

> c) P0ody-files actually archives the stories

Oh, it’s just that I remember looking for several stories there that 1) have previously been linked to through the bot and thus P0ody-files and 2) were later removed from ff.net, and P0ody-files told it couldn’t find those stories\offer anything to download. I don’t remember precise names for the stories, so I may be mistaken.

Theoretically, is it feasible, in your opinion, to automate torrented distribution of archived stories? I’d think online storages like Google Drive and Dropbox would be an option, but they don’t offer unlimited space, and may have problems when interacting with bots.

**Comment by tusing** [comment]
> To remove possible misunderstanding: I meant an ability for the bot to accept a link to a subreddit thread 

Heh. I just remembered this feature request this morning. ```linksub(...)``` has just been implemented, but it's terribly inefficient, and I'm working on something to make it much faster (albeit no less messy) - check out [1.3-slimcomments](https://github.com/tusing/reddit-ffn-bot/tree/1.3-slimcomments).

**Comment by tusing** [comment]
This has now been fully implemented.
